version: '3.3'

services:
          
  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto:1.5.6
    #network_mode: host
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/config:/mosquitto/config:rw
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
      
networks:
  default:
    driver: "bridge"
