version: '2'

services:

  mosquitto:
    hostname: mosquitto
    image: eclipse-mosquitto:2.0.7
    container_name: mqttlocal
    #network_mode: host
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config/
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log/mosquitto.log
    ports:
      - "1883:1883" # MQTT Port
      - "9001:9001" # WS Port
#    environment:
#      - TZ=Europe/Berlin